import { IrrRequest, Industry } from './types.ts';

function slugify(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 40);
}

const INDUSTRY_CONTEXT: Record<Industry, string> = {
  pharma: 'FDA-regulated pharma/biologic/device GMP. Regs: 21 CFR 210/211, 820, ICH Q7/Q9/Q10. Decisions: batch release, CAPA closure, deviation disposition, change control, OOS closure.',
  '503b': '503B sterile compounding under cGMP + USP <797>/<71>/<85>/<800>. Decisions: CSP batch release, EM excursion, sterility OOS, media fill failure, BUD extension. Sterility assurance is the core exposure.',
  food: 'FDA food under FSMA (21 CFR 117). Decisions: finished product release, CCP deviation, raw material acceptance, supplier verification, recall.',
  cosmetics: 'FDA cosmetics under MoCRA (FD&C Act 605-609). Decisions: safety substantiation, adverse event classification, ingredient/supplier change, recall.',
};

const IRR_COMMERCIAL_OBJECTIVE =
  'Prove that a QMS-documented decision cannot demonstrate why the reasoning behind it is defensible without a record captured, pressure-tested, and preserved before the decision was finalized.';

export function buildIrrContract(input: IrrRequest) {
  const contractId = `EC-IRR-${slugify(input.decisionDescription)}-${slugify(input.decisionOwner)}`;

  return {
    contractId,
    purpose: `Governs the Inspection Response Record for the decision: \"${input.decisionDescription}\".`,
    audience: input.audience,
    commercialObjective: IRR_COMMERCIAL_OBJECTIVE,
    requiredInputs: ['decisionDescription', 'audience', 'evidenceSummary', 'riskContext', 'decisionOwner', 'authorizationDate'],
    requiredOutputs: [
      'investigatorQuestion', 'authorizationSummary', 'evidenceReviewed_list',
      'riskEvaluation', 'alternativesConsidered', 'authorizationRationale',
      'regulatoryAlignment', 'residualExposureStatement', 'knownLimitations',
      'gapFlags_list', 'criticalGapsRanked_list', 'defensibilityRating', 'executiveBrief',
      'executiveBriefBreakdown_list', 'evidenceMatrix_list', 'evidenceTraceability_list',
      'claimStatus_list', 'unsupportedClaims_list', 'inspectorChallenge_list',
      'remediationScaffold_list',
    ],
    narrativePattern: 'NP-002',
    reasoningRules: ['RG-001', 'RG-004', 'RG-005', 'RG-009'],
    evidenceRules: ['ES-001', 'ES-003', 'ES-004', 'ES-006'],
    constraints: [
      'Must not name a specific real company in public-facing copy without sanitization.',
      'Must not claim this record replaces or is generated by a QMS, document repository, validation system, or CAPA/deviation tool -- those store documentation; this records the authorization logic behind the decision.',
      `Regulatory and decision context for this industry (${input.industry}): ${INDUSTRY_CONTEXT[input.industry]}`,
      'defensibilityRating must be exactly one of: \"Critical Exposure\", \"At Risk\", \"Defensible with Gaps\", \"Inspection-Ready\".',
      'Each entry in claimStatus_list classifies one specific factual claim in the rationale as exactly one of: \"Claimed in rationale\", \"Supported by attached evidence\", \"Not traceable in record\". A value cited without supporting evidence in the inputs is \"Not traceable in record\" -- never \"Supported by attached evidence\".',
      'unsupportedClaims_list entries are framed as what the record fails to establish -- never as coaching on what to say or not say to an investigator.',
      'remediationScaffold_list entries are documentation SCAFFOLDS, never finished prose. Every specific -- value, result, ID, date, method, instrument or worksheet name, signatory, title, acceptance criterion -- MUST be a bracketed blank such as [reference], [name], [date]. A signatory is a required ROLE, never an invented name. Fabricating a real-looking specific in a remediation scaffold is the most serious failure this record can contain.',
      'Every distinct deficiency, gap, or unsupported claim is explained in full exactly once, in its primary home section (knownLimitations or unsupportedClaims_list). Every other section that touches the same deficiency refers to it by short name only -- it does not restate the explanation.',
      'criticalGapsRanked_list names the 2-3 single most inspection-critical gaps, ranked by severity, by specific name -- not a repeat of numeric counts shown elsewhere. This is the first thing a reader sees after the executive brief; it must be legible on its own without reading anything else.',
      'Every entry in gapFlags_list pairs the gap with a specific imperative next action (e.g., \"Obtain and document the original authorization date before inspection\"), never a passive statement of absence alone.',
      'knownLimitations is a single string field, not a list -- write it as flowing prose (one or more paragraphs), never as a JSON array or bullet list. Within that prose, name each distinct limitation and close it with a specific imperative next action, never a passive statement of absence alone.',
      `Decision under review: ${input.decisionDescription}`,
      `Evidence summary provided: ${input.evidenceSummary}`,
      `Risk context provided: ${input.riskContext}`,
    ],
    acceptanceCriteria: [
      'Every claim asserted in authorizationRationale is either traceable to evidenceReviewed_list or explicitly named in unsupportedClaims_list -- no fact appears in the rationale without one of those two homes.',
      'gapFlags_list names every distinct documentation gap identified elsewhere in the record; no gap is mentioned in knownLimitations without a corresponding flag.',
      'remediationScaffold_list contains only bracketed-blank scaffolds, never a finished paragraph with real-looking specifics.',
      'inspectorChallenge_list grounds every response in the record -- never asserts a fact not present in the inputs.',
      'criticalGapsRanked_list names specific gaps, not a repeat of counts already shown in the scorecard.',
      'No deficiency\'s full explanation appears in more than one section.',
      'Every gapFlags_list entry ends in an imperative action, not a bare statement of absence. knownLimitations, as prose, closes each limitation it names with an imperative action the same way.',
    ],
    traceability: { inheritsFrom: ['Chapter 3', 'Chapter 5', 'Chapter 6'] },
    versionMetadata: { version: '2.1.0', status: 'approved', dependencies: ['Chapter 1', 'Chapter 7', 'Chapter 8'] },
  };
}
