import { serve } from 'https://deno.land/std@0.168.0/http/server.ts';

const SUPABASE_URL = Deno.env.get('SUPABASE_URL') ?? '';
const SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '';
const GENERATE_RECORD_URL = 'https://www.complianceworxs.com/api/generate-record';
const GENERATION_STATUS_URL = 'https://www.complianceworxs.com/api/generation-status';

const POLL_INTERVAL_MS = 5000;
const TEST_DEADLINE_MS = 350_000; // above the 260s internal deadline + retry headroom

function sbHeaders(): Record<string, string> {
  return { 'Content-Type': 'application/json', apikey: SERVICE_ROLE_KEY, Authorization: `Bearer ${SERVICE_ROLE_KEY}`, Prefer: 'return=representation' };
}

function slugify(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 40);
}

const INDUSTRY_CONTEXT: Record<string, string> = {
  pharma: 'FDA-regulated pharma/biologic/device GMP. Regs: 21 CFR 210/211, 820, ICH Q7/Q9/Q10. Decisions: batch release, CAPA closure, deviation disposition, change control, OOS closure.',
  '503b': '503B sterile compounding under cGMP + USP <797>/<71>/<85>/<800>. Decisions: CSP batch release, EM excursion, sterility OOS, media fill failure, BUD extension. Sterility assurance is the core exposure.',
  food: 'FDA food under FSMA (21 CFR 117). Decisions: finished product release, CCP deviation, raw material acceptance, supplier verification, recall.',
  cosmetics: 'FDA cosmetics under MoCRA (FD&C Act 605-609). Decisions: safety substantiation, adverse event classification, ingredient/supplier change, recall.',
};

const IRR_COMMERCIAL_OBJECTIVE =
  'Prove that a QMS-documented decision cannot demonstrate why the reasoning behind it is defensible without a record captured, pressure-tested, and preserved before the decision was finalized.';

function buildIrrContract(input: any) {
  const contractId = `EC-IRR-${slugify(input.decisionDescription)}-${slugify(input.decisionOwner)}`;
  return {
    contractId,
    purpose: `Governs the Inspection Response Record for the decision: "${input.decisionDescription}".`,
    audience: input.audience,
    commercialObjective: IRR_COMMERCIAL_OBJECTIVE,
    requiredInputs: ['decisionDescription', 'audience', 'evidenceSummary', 'riskContext', 'decisionOwner', 'authorizationDate'],
    requiredOutputs: [
      'investigatorQuestion', 'authorizationSummary', 'evidenceReviewed_list',
      'riskEvaluation', 'alternativesConsidered', 'authorizationRationale',
      'regulatoryAlignment', 'residualExposureStatement', 'knownLimitations',
      'gapFlags_list', 'criticalGapsRanked_list', 'defensibilityRating', 'executiveBrief',
      'executiveBriefBreakdown_list', 'evidenceMatrix_list', 'evidenceTraceability_list',
      'claimStatus_list', 'unsupportedClaims_list', 'inspectorChallenge_list',
      'remediationScaffold_list',
    ],
    narrativePattern: 'NP-002',
    reasoningRules: ['RG-001', 'RG-004', 'RG-005', 'RG-009'],
    evidenceRules: ['ES-001', 'ES-003', 'ES-004', 'ES-006'],
    constraints: [
      'Must not name a specific real company in public-facing copy without sanitization.',
      'Must not claim this record replaces or is generated by a QMS, document repository, validation system, or CAPA/deviation tool -- those store documentation; this records the authorization logic behind the decision.',
      `Regulatory and decision context for this industry (${input.industry}): ${INDUSTRY_CONTEXT[input.industry] ?? ''}`,
      'defensibilityRating must be exactly one of: "Critical Exposure", "At Risk", "Defensible with Gaps", "Inspection-Ready".',
      'Each entry in claimStatus_list classifies one specific factual claim in the rationale as exactly one of: "Claimed in rationale", "Supported by attached evidence", "Not traceable in record". A value cited without supporting evidence in the inputs is "Not traceable in record" -- never "Supported by attached evidence".',
      'unsupportedClaims_list entries are framed as what the record fails to establish -- never as coaching on what to say or not say to an investigator.',
      'remediationScaffold_list entries are documentation SCAFFOLDS, never finished prose. Every specific -- value, result, ID, date, method, instrument or worksheet name, signatory, title, acceptance criterion -- MUST be a bracketed blank such as [reference], [name], [date]. A signatory is a required ROLE, never an invented name. Fabricating a real-looking specific in a remediation scaffold is the most serious failure this record can contain.',
      'Every distinct deficiency, gap, or unsupported claim is explained in full exactly once, in its primary home section (knownLimitations or unsupportedClaims_list). Every other section that touches the same deficiency refers to it by short name only -- it does not restate the explanation.',
      'criticalGapsRanked_list names the 2-3 single most inspection-critical gaps, ranked by severity, by specific name -- not a repeat of numeric counts shown elsewhere. This is the first thing a reader sees after the executive brief; it must be legible on its own without reading anything else.',
      'Every entry in gapFlags_list pairs the gap with a specific imperative next action (e.g., "Obtain and document the original authorization date before inspection"), never a passive statement of absence alone.',
      'knownLimitations is a single string field, not a list -- write it as flowing prose (one or more paragraphs), never as a JSON array or bullet list. Within that prose, name each distinct limitation and close it with a specific imperative next action, never a passive statement of absence alone.',
      `Decision under review: ${input.decisionDescription}`,
      `Evidence summary provided: ${input.evidenceSummary}`,
      `Risk context provided: ${input.riskContext}`,
    ],
    acceptanceCriteria: [
      'Every claim asserted in authorizationRationale is either traceable to evidenceReviewed_list or explicitly named in unsupportedClaims_list -- no fact appears in the rationale without one of those two homes.',
      'gapFlags_list names every distinct documentation gap identified elsewhere in the record; no gap is mentioned in knownLimitations without a corresponding flag.',
      'remediationScaffold_list contains only bracketed-blank scaffolds, never a finished paragraph with real-looking specifics.',
      'inspectorChallenge_list grounds every response in the record -- never asserts a fact not present in the inputs.',
      'criticalGapsRanked_list names specific gaps, not a repeat of counts already shown in the scorecard.',
      "No deficiency's full explanation appears in more than one section.",
      'Every gapFlags_list entry ends in an imperative action, not a bare statement of absence. knownLimitations, as prose, closes each limitation it names with an imperative action the same way.',
    ],
    traceability: { inheritsFrom: ['Chapter 3', 'Chapter 5', 'Chapter 6'] },
    versionMetadata: { version: '2.1.0', status: 'approved', dependencies: ['Chapter 1', 'Chapter 7', 'Chapter 8'] },
  };
}

async function callJson(url: string, body: unknown, timeoutMs = 15000): Promise<{ status: number; body: any }> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetch(url, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body), signal: controller.signal });
    const text = await res.text();
    let json: any;
    try { json = JSON.parse(text); } catch (e) { throw new Error(`Upstream ${url} returned invalid JSON (status=${res.status}): ${(e as Error).message}; body=${text.slice(0, 500)}`); }
    return { status: res.status, body: json };
  } finally {
    clearTimeout(timer);
  }
}

async function updateRun(runId: string, patch: Record<string, unknown>) {
  const res = await fetch(`${SUPABASE_URL}/rest/v1/irr_regression_runs?run_id=eq.${runId}`, { method: 'PATCH', headers: sbHeaders(), body: JSON.stringify(patch) });
  if (!res.ok) { const text = await res.text(); console.error(`Failed to update run ${runId}: ${text.slice(0, 500)}`); }
}

function sleep(ms: number) { return new Promise((r) => setTimeout(r, ms)); }

async function runTest(runId: string, input: any) {
  const t0 = Date.now();
  const supaBase = `${SUPABASE_URL}/functions/v1`;

  const contract = buildIrrContract(input);

  const validation = await callJson(`${supaBase}/validate-editorial-contract`, contract);
  const contractValidationInitial = validation.body?.status === 'valid';
  if (!contractValidationInitial) {
    await finish(runId, t0, { overall: 'FAIL', contract: 'FAIL', schema: 'N/A', json: 'N/A', terminal: 'contract_invalid', retries: 0, detail: validation.body });
    return;
  }

  const compiled = await callJson(`${supaBase}/compile-editorial-contract`, contract);
  if (compiled.body?.status !== 'compiled') {
    await finish(runId, t0, { overall: 'FAIL', contract: 'FAIL', schema: 'N/A', json: 'N/A', terminal: 'execution_compile_failed', retries: 0, detail: compiled.body });
    return;
  }
  const executionSpecification = compiled.body.executionSpecification;

  const promptResult = await callJson(`${supaBase}/compile-prompt-specification`, { executionSpecification, targetRuntime: 'claude' });
  if (promptResult.body?.status !== 'compiled') {
    await finish(runId, t0, { overall: 'FAIL', contract: 'FAIL', schema: 'N/A', json: 'N/A', terminal: 'prompt_package_invalid', retries: 0, detail: promptResult.body });
    return;
  }
  const promptPackage = promptResult.body.promptPackage;

  let genRes;
  try {
    genRes = await callJson(GENERATE_RECORD_URL, { promptPackage, userVariables: input, maxTokens: 16000 }, 15000);
  } catch (err) {
    await finish(runId, t0, { overall: 'FAIL', contract: 'FAIL', schema: 'N/A', json: 'N/A', terminal: 'generate_record_unreachable', retries: 0, detail: { message: (err as Error).message } });
    return;
  }
  const generationId = genRes.body?.generationId;
  if (!generationId) {
    await finish(runId, t0, { overall: 'FAIL', contract: 'FAIL', schema: 'N/A', json: 'N/A', terminal: 'generate_record_rejected', retries: 0, detail: genRes.body });
    return;
  }
  await updateRun(runId, { generation_id: generationId });

  let statusBody: any = null;
  while (Date.now() - t0 < TEST_DEADLINE_MS) {
    await sleep(POLL_INTERVAL_MS);
    const getRes = await fetch(`${GENERATION_STATUS_URL}?generationId=${generationId}`);
    statusBody = await getRes.json();
    if (statusBody.status === 'executed' || statusBody.status === 'failed' || statusBody.status === 'timed_out') break;
  }

  if (!statusBody || statusBody.status === 'pending') {
    await finish(runId, t0, { overall: 'FAIL', contract: 'FAIL', schema: 'N/A', json: 'N/A', terminal: 'test_harness_deadline_exceeded', retries: 0, detail: statusBody });
    return;
  }

  // Pull attempt_count directly -- generation-status.ts's public contract doesn't expose it.
  const rowRes = await fetch(`${SUPABASE_URL}/rest/v1/runtime_generations?generation_id=eq.${generationId}&select=attempt_count,issues`, { headers: { apikey: SERVICE_ROLE_KEY, Authorization: `Bearer ${SERVICE_ROLE_KEY}` } });
  const rowJson = await rowRes.json();
  const retries = Array.isArray(rowJson) && rowJson[0] ? rowJson[0].attempt_count : 0;

  if (statusBody.status === 'failed' || statusBody.status === 'timed_out') {
    await finish(runId, t0, { overall: 'FAIL', contract: 'FAIL', schema: 'FAIL', json: 'FAIL', terminal: statusBody.status, retries, detail: statusBody.issues });
    return;
  }

  // statusBody.status === 'executed'
  const jsonValidation = statusBody.artifact?.structuredResponse ? 'PASS' : 'FAIL';
  const schemaValidation = statusBody.runtimeManifest?.schemaValidation === 'passed' ? 'PASS' : 'FAIL';

  const outputValidation = await callJson(`${supaBase}/validate-editorial-output`, {
    artifact: statusBody.artifact,
    executionSpecification,
    promptPackage,
    runtimeManifest: statusBody.runtimeManifest,
    skipEditorialReview: true,
  });
  const terminalState = outputValidation.body?.terminalState ?? 'REJECT';
  const contractValidation = terminalState === 'PASS' ? 'PASS' : 'FAIL';

  const overall = (jsonValidation === 'PASS' && schemaValidation === 'PASS' && contractValidation === 'PASS') ? 'PASS' : 'FAIL';

  await finish(runId, t0, {
    overall,
    contract: contractValidation,
    schema: schemaValidation,
    json: jsonValidation,
    terminal: 'completed',
    retries,
    detail: { terminalState, blockingReasons: outputValidation.body?.blockingReasons ?? null },
  });
}

async function finish(runId: string, t0: number, r: { overall: string; contract: string; schema: string; json: string; terminal: string; retries: number; detail: unknown }) {
  await updateRun(runId, {
    status: 'done',
    runtime_seconds: Math.round((Date.now() - t0) / 100) / 10,
    terminal_state: r.terminal,
    retry_count: r.retries,
    schema_validation: r.schema,
    contract_validation: r.contract,
    json_validation: r.json,
    overall_result: r.overall,
    detail: r.detail,
    finished_at: new Date().toISOString(),
  });
}

serve(async (req) => {
  if (req.method !== 'POST') return new Response(JSON.stringify({ error: 'POST only' }), { status: 405 });
  const body = await req.json();
  const { testName, input } = body ?? {};
  if (!input) return new Response(JSON.stringify({ error: 'input is required' }), { status: 400 });

  const insertRes = await fetch(`${SUPABASE_URL}/rest/v1/irr_regression_runs`, {
    method: 'POST',
    headers: sbHeaders(),
    body: JSON.stringify([{ test_name: testName ?? 'unnamed', input_payload: input, status: 'running' }]),
  });
  const inserted = await insertRes.json();
  const runId = inserted?.[0]?.run_id;

  // @ts-ignore
  EdgeRuntime.waitUntil(runTest(runId, input));

  return new Response(JSON.stringify({ run_id: runId, status: 'started' }), { status: 202, headers: { 'Content-Type': 'application/json' } });
});
