import { BatchReviewRequest } from './types.ts';

function slugify(text: string): string {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 40);
}

const BATCH_REVIEW_COMMERCIAL_OBJECTIVE =
  'Prove that a batch disposition graded against an evidence-sufficiency standard exposes gaps a standard batch review would miss, and route each gap to the Inspection Response Record that would have prevented it.';

const GRADING_CRITERIA = ['reliability', 'objectivity', 'completeness', 'consistency', 'relevance'];

export function buildBatchReviewContract(input: BatchReviewRequest) {
  const contractId = `EC-BATCHREVIEW-${slugify(input.decisionDomain)}-${slugify(input.submittedMaterial.slice(0, 30))}`;

  return {
    contractId,
    purpose: `Governs a Batch Review by Exception for decision domain: "${input.decisionDomain}".`,
    audience: 'Quality Director / batch disposition reviewer',
    commercialObjective: BATCH_REVIEW_COMMERCIAL_OBJECTIVE,
    requiredInputs: ['decisionDomain', 'submittedMaterial'],
    requiredOutputs: ['reviewSummary', 'findings_list', 'evidenceNotLocated_list', 'recommendedActions_list', 'irrReferences_list'],
    narrativePattern: 'NP-002',
    reasoningRules: ['RG-001', 'RG-003', 'RG-009'],
    evidenceRules: ['ES-001', 'ES-004', 'ES-006'],
    constraints: [
      'Must not name a specific real company in public-facing copy without sanitization.',
      'Must not claim this review replaces or is generated by a QMS, document repository, validation system, or CAPA/deviation tool.',
      `Grading rubric: every finding is graded against these five dimensions -- ${GRADING_CRITERIA.join(', ')} (Traci Waldecker's Evidence Sufficiency Framework).`,
      'evidenceNotLocated_list is scoped strictly to the submitted material -- never infer the existence of evidence not actually provided.',
      'recommendedActions_list is documentation-only -- never a prescriptive process or corrective instruction.',
      'BR-001: every finding SHALL include at least one verbatim quoted evidence anchor from the submitted material -- not summarized, not paraphrased, not merely referenced.',
      `Decision domain under review: ${input.decisionDomain}`,
      `Submitted material: ${input.submittedMaterial}`,
    ],
    acceptanceCriteria: [
      'Every finding in findings_list contains at least one verbatim quoted evidence anchor from the submitted material (BR-001).',
      'evidenceNotLocated_list names only gaps genuinely absent from the submitted material, never inferred from outside knowledge.',
      'recommendedActions_list contains documentation-only actions, never corrective or procedural instructions.',
      'Each finding, where applicable, is routed in irrReferences_list to the matching decision domain.',
    ],
    traceability: { inheritsFrom: ['Chapter 3', 'Chapter 5', 'Chapter 6'] },
    versionMetadata: { version: '1.0.0', status: 'approved', dependencies: ['Chapter 1', 'Chapter 7', 'Chapter 8'] },
  };
}

export { GRADING_CRITERIA };
