ALTER TABLE warm_outbound_staging
  ADD COLUMN IF NOT EXISTS ai_icebreaker TEXT,
  ADD COLUMN IF NOT EXISTS personalization_status TEXT DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS personalized_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS review_status TEXT DEFAULT 'pending_review';

CREATE INDEX IF NOT EXISTS idx_warm_personalization_status 
  ON warm_outbound_staging(personalization_status) 
  WHERE personalization_status IN ('pending','failed');

COMMENT ON COLUMN warm_outbound_staging.ai_icebreaker IS 
  'AI-generated 1-sentence opening line. Inspector-frame. Generated by personalization-engine cron.';
COMMENT ON COLUMN warm_outbound_staging.review_status IS 
  'Human-in-loop gate: pending_review | approved | rejected. Only approved icebreakers ship in outreach.';