CREATE TABLE IF NOT EXISTS conversion_playbook_decisions (
  id BIGSERIAL PRIMARY KEY,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  snapshot_id BIGINT REFERENCES posthog_conversion_daily(id),

  -- The single morning decision
  primary_action TEXT NOT NULL,          -- "rewrite_universal_headline" | "rewrite_main_headline" | "expand_page_specific_copy" | "fix_broken_gate" | "hold" | "push_outbound" | "verify_cta_tracking"
  primary_target TEXT,                    -- which gate or page
  current_metric TEXT,                    -- e.g. "2.1% on 89 impressions"
  recommendation TEXT NOT NULL,           -- the one-line recommendation
  recommended_copy_variant JSONB,         -- pre-written copy variant ready to ship
  expected_lift TEXT,                     -- e.g. "Target 5-8% conversion"

  -- Status tracking
  status TEXT NOT NULL DEFAULT 'pending', -- pending | approved | rejected | shipped | expired
  approved_at TIMESTAMPTZ,
  shipped_at TIMESTAMPTZ,

  -- Full reasoning trail
  thresholds_applied JSONB,
  raw_metrics JSONB
);

CREATE INDEX IF NOT EXISTS idx_playbook_generated_at ON conversion_playbook_decisions(generated_at DESC);
CREATE INDEX IF NOT EXISTS idx_playbook_status ON conversion_playbook_decisions(status, generated_at DESC);

COMMENT ON TABLE conversion_playbook_decisions IS 'Daily conversion playbook output. Generated by conversion-playbook edge function 30 min after posthog-conversion-monitor. One recommended action per day with pre-written copy variant.';