
ALTER TABLE leads
  ADD COLUMN IF NOT EXISTS name        TEXT,
  ADD COLUMN IF NOT EXISTS title       TEXT,
  ADD COLUMN IF NOT EXISTS company     TEXT,
  ADD COLUMN IF NOT EXISTS answers     JSONB,
  ADD COLUMN IF NOT EXISTS gaps        JSONB,
  ADD COLUMN IF NOT EXISTS primary_gap TEXT,
  ADD COLUMN IF NOT EXISTS risk_level  TEXT;
