
ALTER TABLE exposure_snapshots
  ADD COLUMN IF NOT EXISTS subspec text,
  ADD COLUMN IF NOT EXISTS citation_primary text,
  ADD COLUMN IF NOT EXISTS citation_ich text,
  ADD COLUMN IF NOT EXISTS regulatory_framework text,
  ADD COLUMN IF NOT EXISTS report_id_example text,
  ADD COLUMN IF NOT EXISTS product_lot_example text,
  ADD COLUMN IF NOT EXISTS scene_para_1 text,
  ADD COLUMN IF NOT EXISTS scene_para_2 text,
  ADD COLUMN IF NOT EXISTS inspector_short_quote text,
  ADD COLUMN IF NOT EXISTS inspector_long_quote text,
  ADD COLUMN IF NOT EXISTS inspector_quote_3 text,
  ADD COLUMN IF NOT EXISTS investigator_role text,
  ADD COLUMN IF NOT EXISTS decision_subject text,
  ADD COLUMN IF NOT EXISTS narrative2_lead text,
  ADD COLUMN IF NOT EXISTS narrative2_para1 text,
  ADD COLUMN IF NOT EXISTS narrative2_para4 text,
  ADD COLUMN IF NOT EXISTS eval_headline text,
  ADD COLUMN IF NOT EXISTS eval_p1 text,
  ADD COLUMN IF NOT EXISTS eval_p2 text,
  ADD COLUMN IF NOT EXISTS eval_p3 text,
  ADD COLUMN IF NOT EXISTS anchor_text text,
  ADD COLUMN IF NOT EXISTS gap_h2 text,
  ADD COLUMN IF NOT EXISTS gap_list jsonb,
  ADD COLUMN IF NOT EXISTS gap_emphasis text,
  ADD COLUMN IF NOT EXISTS field_1_name text,
  ADD COLUMN IF NOT EXISTS field_1_desc text,
  ADD COLUMN IF NOT EXISTS field_2_name text,
  ADD COLUMN IF NOT EXISTS field_2_desc text,
  ADD COLUMN IF NOT EXISTS field_3_name text,
  ADD COLUMN IF NOT EXISTS field_3_desc text,
  ADD COLUMN IF NOT EXISTS field_4_name text,
  ADD COLUMN IF NOT EXISTS field_4_desc text,
  ADD COLUMN IF NOT EXISTS field_5_name text,
  ADD COLUMN IF NOT EXISTS field_5_desc text,
  ADD COLUMN IF NOT EXISTS ddr_record_id text,
  ADD COLUMN IF NOT EXISTS ddr_decision text,
  ADD COLUMN IF NOT EXISTS ddr_authorizer text,
  ADD COLUMN IF NOT EXISTS ddr_authority_basis text,
  ADD COLUMN IF NOT EXISTS ddr_evidence_list text,
  ADD COLUMN IF NOT EXISTS ddr_alternatives text,
  ADD COLUMN IF NOT EXISTS ddr_timestamp text,
  ADD COLUMN IF NOT EXISTS page_active boolean DEFAULT true;

CREATE INDEX IF NOT EXISTS idx_exposure_snapshots_active_slug ON exposure_snapshots (case_file_slug) WHERE page_active = true;
